# Generated by Django 3.0.5 on 2020-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='claps',
            new_name='palmas',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='parents',
            new_name='responsaveis',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='titulo',
        ),
    ]
