# Generated by Django 3.0.5 on 2020-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200408_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
