# Generated by Django 3.0.5 on 2020-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20200408_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/uploads'),
        ),
    ]
