# Generated by Django 3.0.5 on 2020-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200408_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/images/uploads'),
        ),
    ]
