# Generated by Django 3.0.5 on 2020-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20200408_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagem',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
