# Generated by Django 3.0.5 on 2020-04-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_photo_palmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='palmas',
        ),
    ]
