# Generated by Django 3.0.5 on 2020-04-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_remove_photo_palmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='responsaveis',
        ),
    ]
